---
driver:
  name: ec2
  aws_ssh_key_id: stephengoncher
  instance_type: t2.micro

transport: 
  ssh_key: ~/.ssh/stephengoncher

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7
  - name: amazon-linux
    driver:
      image_id: ami-08842d60
    transport:
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[webserver::apache]
      - recipe[webserver::git]
    attributes:
